########################################################
# KSR-SQL-Whitelist - Configuration
# Plugin by Timy Liniger (https://ksrminecraft.ch/)
########################################################

# ================================
# MySQL Database Settings
# ================================
mysql:
  host: localhost
  port: 3306
  database: KSRMC-Registration
  user: root
  password: example
  table: mysql_whitelist
  column_uuid: UUID
  column_name: user
  useSSL: false
  serverTimezone: UTC

# ================================
# Whitelist Settings
# ================================

# Ob die Whitelist beim Start aktiviert ist (true/false)
enabled: true

# Kick-Messages

kick:
  not_whitelisted: "&cLeider bist du nicht auf unserer Whitelist.&r\n&7Registriere dich auf https://ksrminecraft.ch."
  db_error: "&cEs gab einen internen Fehler mit der Datenbank.&r\n&7Bitte versuche es sp√§ter erneut oder melde dich auf unserem Discord."

